### ISSUE TITLE
Usage of native Promise

### ISSUE THREAD

**Issue by asudoh** [ibm-js/sdk#5]
Latest Firefox/Chrome supports Promise natively. We may want to use it directly (rather than dojo/Deferred) for those browsers.

One problem with that is difference in Promise constructor. [Promise in Dojo](https://github.com/csnover/dojo2-core/blob/2.0/promise/Promise.js) currently assumes it's created from dojo/Deferred. Promise in ECMAScript is created via Promise constructor.

Some possible approaches to solve that would be:
- Encourage Dojo community to support ECMAScript interface in their Promise
- Use another Promise library supporting ECMAScript interface, like [Q library](https://github.com/kriskowal/q)
- Create a thin wrapper by our own, like below:

``` javascript
define(["dojo/Deferred"], function (Deferred) {
    if (typeof Promise === "undefined") {
        function Promise(resolver) {
            if (typeof resolver !== "function") {
                throw new TypeError("resolver must be a function.");
            }
            var dfd = new Deferred();
            try {
                resolver(dfd.resolve, dfd.reject);
            } catch (e) {
                dfd.reject(e);
            }
            return dfd.promise;
        }
    }
});
```

CC: @cjolif, @wkeese

**Comment by cjolif** [comment]
I'm hearing a lot about Q recently. So maybe that's a good alternative. However I don't find a reference on their site claiming they are ES6 compatible, do you have a pointer to that @asudoh? thanks.

**Comment by asudoh** [comment]
Not sure if there is a better link, but I see: http://stackoverflow.com/questions/22294425/promises-ecmascript-6-vs-3rd-party-libraries#answer-22331345

**Comment by pruzand** [comment]
Q is indeed popular but there are lots of discussions about its performances that would not be that great, but I don't have any link to bench involving dojo Deferred (there's this one though https://github.com/petkaantonov/bluebird/blob/master/benchmark/stats/latest.md, done by blubird (another promise lib) author, so...) .
It seems to me that the Dojo Deferred is pretty solid (at least that was my vision when it was proposed/developped and from the various feedbacks from the community, did not do any comparative bench), so maybe it would be a good thing to propose to enhance Dojo Deferred API to match ES spec.
Also, not sure it is a problem, but if ibm-js uses Q promises (or any other framework), and still use some dojo core api, we will have a mix of different promise impl that would need to be handled carefully. Might not be a real issue, but to bear in mind.

**Comment by asudoh** [comment]
@pruzand Thank you for sharing info/thoughts. Your comment has made me wonder what the progress of Dojo2 is. I see Colin has [a GitHub repo](https://github.com/csnover/dojo2-core/) for that, but it seems not updated recently.

**Comment by cjolif** [comment]
@asudoh there is another newer repo: https://github.com/csnover/core (in TypeScript)

**Comment by wkeese** [comment]
I'm working now to get rid of the dojo dependencies, and this is a big one.

http://www.html5rocks.com/en/tutorials/es6/promises/ is useful.  It talks about the Promise native support in Chrome and FF, and also mentions the [es6-promise](https://github.com/jakearchibald/es6-promise) polyfill.   It would be a bit annoying to use since it's written in sweetjs (needs to be compiled to plain javascript), but at least the modules go to AMD.

The website mentions some other libraries too.   They seem big, but maybe if you just require() the modules you need it's OK.  Here's my take on them:
- [Q](https://github.com/kriskowal/q) - Besides the performance concerns that @pruzand mentioned, this is over 30 pages of code.  I'm not sure how much it is minified [and zipped], but it sounds much too big.  I see the code is bloated by support for old IE (things like an implementation for Object.keys).   It also duplicates the code @asudoh has in decor/schedule, although I guess that will be true for every promise library.  (Perhaps decor/schedule should be replaced w/a call to a resolved promises `.then()` method?)  And finally, it's not AMD.
- [when](https://github.com/cujojs/when) - Says it has small size but I didn't measure it.  UMD format, so it will be loadable via AMD.  It also has a [es6 promise shim](https://github.com/cujojs/when/blob/master/docs/es6-promise-shim.md), although not sure how loading that is different than loading the individual modules.
- [WinJS](http://msdn.microsoft.com/en-us/library/windows/apps/br211867.aspx) - Microsoft only???
- [RSVP.js](https://github.com/tildeio/rsvp.js) - The shim is actually a subset of RSVP.  RSVP has an AMD release but it's also 30 pages of code.  Incidentally, it's written use sweetjs macros, but the release is already compiled into javascript.

I'm unclear on what exactly "polyfill" means for promises, compared to using one of the above libraries..  If it's just combining a bunch of modules and creating a global variable called Promise, then we don't want want it.

Also, I tried using jQuery promises but was disappointed.  I pushed my work to wkeese/delite@affe7ab93a2853f6874d0a05a9741862489b9b2e, but as the comment says:

> It doesn't work currently because `$.when()` has weird behavior.
> when() is supposed to branch depending on whether or not the argument is a promise.
> However, the check it actually does is `jQuery.isFunction( subordinate.promise )`, where
> subordinate is the argument, so it doesn't work if you pass in a promise, (since there's no
> `promise.promise()` function), nor even if you pass in a normal Deferred (since Deferred#promise
> is an object, not a function).

jQuery's non-standard behavior is also mentioned in http://www.html5rocks.com/en/tutorials/es6/promises/.

For all of these, @cjolif would have to check out the licenses.

**Comment by wkeese** [comment]
More notes: I was looking at the [Promise spec](http://www.html5rocks.com/en/tutorials/es6/promises/#toc-api) to see if it has everything we need.  Glad to see it supports `all()`, but one thing missing is `when()`.   But looks like there's another API for the same thing, at least on Chrome 36: using `Promise.resolve()`:

Passing a scalar:

```
> Promise.resolve("scalar").then(function(val){ console.log("resolved as " + val); },
> function(err){ console.log("err as", err); });
resolved as scalar 
```

Passing another promise:

```
> var p = new Promise(function(resolve) { setTimeout(resolve.bind(null, "hi"), 5000); }); 
> Promise.resolve(p).then(function(val){ console.log("resolved as " + val); },
> function(err){ console.log("err as", err); });
resolved as hi
```

Passing a promise that errors:

```
> var p = new Promise(function(resolve, reject) { reject(new Error("bill's error")); }); 
> Promise.resolve(p).then(function(val){ console.log("resolved as " + val); }, 
> function(err){ console.log("err as", err); });
err as 
Error {stack: (...), message: "bill's error"}
```

**Comment by cjolif** [comment]
All of them are MIT-based except WinJS which is Apache License. That should be ok. I would tend however to not adopt WinJS as I'm not sure how much of WinJS we would have to consume to just use the promises.

>  It talks about the Promise native support in Chrome and FF, and also mentions the es6-promise polyfill. It would be a bit annoying to use since it's written in sweetjs (needs to be compiled to plain javascript), but at least the modules go to AMD.

es6-shim looks ok. It is small and the built version is loadable using AMD, after all we don't really care in which language it was written as soon as we are not the ones maintaining it. The only concerns I have with that one is that fisrt it seems to be a subset of RSVP.js. So the question is, how quickly and consistently are fixes in RSVP.js included into es6-shim? Second it also says that to get nice debugging you have to use RSVP.js. I know that one complaint we often hear about promises is hard debugging, so I would not like us to tighten with a solution that makes it even harder than in Dojo.

> when - Says it has small size but I didn't measure it. UMD format, so it will be loadable via AMD. It also has a es6 promise shim, although not sure how loading that is different than loading the individual modules.

I think the thing is that the shim is providing you with a Promise global object (like es6-shim above) while loading individual modules would not.

**Comment by wkeese** [comment]
> es6-shim looks ok. It is small and the built version is loadable using AMD

Are you sure?  If you are talking about http://s3.amazonaws.com/es6-promises/promise-1.0.0.js, ISTM it redefines `define`, so the AMD load would never complete because the real `define()` function would never be called.

PS: About that rollup file, is also disappointing to load Promise.asap() and Promise.race() even though we aren't using them.   (Also, there's no Promise.asap() in the spec AFAICT.)

**Comment by cjolif** [comment]
> Are you sure? If you are talking about http://s3.amazonaws.com/es6-promises/promise-1.0.0.js, ISTM it redefines define, so the AMD load would never complete because the real define() function would never be called.

Ok. I guess I just read "AMD" or something and did not look at the code itself to double check.

**Comment by clmath** [comment]
Since we will eventually use ES6 Promise I think we should provide a way to leverage an existing Promise implementation in the browser. 
Currently lie.js is used even if the browser provide a promise implementation, which is suboptimal.

We could use a has test to conditionally load lie.js or figure out another solution.

Any ideas ?

**Comment by wkeese** [comment]
It would be easy to write a plugin that loaded lie or returns the native implementation if available.

The only caveat is that lie cannot be rolled into any layer (i.e. it needs to be treated as its own layer)... because layers are not browser-specific.

**Comment by wkeese** [comment]
Actually, this ticket is about using native promises, and  clmath/delite@68f4209 doesn't do that.   This ticket should be left open until ibm-js/requirejs-dplugins#17 is committed and everyone is using that plugin.
